<?php
    $jobCollection = $this->getLoadedJobCollection();
    $iterator = 1;
    $total = $jobCollection->count();
?>

<div class="job-wrapper">
    <ol class="jobs list">
    <?php foreach($jobCollection AS $job): ?>
        <li>
            
            <div class="title">
                <a href="<?= $this->getJobUrl($job); ?>" title="<?= $job->getTitle(); ?>">
                    <?= $job->getTitle(); ?>
                </a>
            </div>

            <div class="department_name">
                <?= __('Department : '); ?>
                <a href="<?= $this->getDepartmentUrl($job); ?>" title="<?= $job->getDepartmentName(); ?>">
                    <?= $job->getDepartmentName(); ?>
                </a>
            </div>

            <div class="type"><?= $job->getType(); ?></div>

            <div class="location"><?= $job->getLocation(); ?></div>

            <div class="date"><?= $this->formatDate($job->getDate()); ?></div>

            <div class="description"><?= $job->getDescription(); ?></div>
        </li>

    <?php endforeach; ?>
    </ol>
</div>